### ISSUE TITLE
Hardcoded table prefix 

### ISSUE THREAD

**Issue by niftycodeltd** [thoughtfulweb/craft-litespeedcache#3]
Hi

I had an issue where my site went down tonight with the following error:

```
Base table or view not found: Table 'database.craft_templatecacheelements' doesn't exit
```

In the following file `vendor/thoughtfulweb/lite-speed-cache/src/services/GetElements.php` we found the table hardcoded with the default `craft` prefix, `->from(['craft_templatecacheelements'])`. However we use a custom prefix with all our installations so this tabel could not be found.

Changing the prefix or the plugin code fixed the error but obvioulsy if we update the plugin in the future this will break again.

Cheers

Peter

**Comment by jsmrtn** [comment]
Fixed by #4. Thanks @JorgeAnzola!
