### ISSUE TITLE
Forms and injecting CSRF tokens in JavaScript

### ISSUE THREAD

**Issue by rogerdawkins** [thoughtfulweb/craft-litespeedcache#5]
I'm using LiteSpeed and your plugin very successfully. However my client has asked for a subscription form on the home page and that is causing an issue with CSRF tokens. I have tried to use your suggestion to inject the token using JavaScript but this is failing as well. I think I understand the reason why it is failing but if I'm right it means your token injection will not work.

The basic issue is that the craft.app.request.getCsrfToken call is a server based request and by the time it is reaches the browser it has been rendered so the browser sees:
`$('form.csrf').prepend('<input type="hidden" name="CRAFT_CSRF_TOKEN" value="ub26Levr...6_A=" />');   `
 (truncated for brevity)
and it is that data that gets cached by LS. Next time the page is called the JavaScript runs but by then the JS has the old token embedded in the string so it never updates.

The reason it never updates is that LS never needs to make a call to the server and a new token is never loaded.

The solution I was going to try was to have the JavaScript make an Ajax call to an uncached page which retrieves the token and that is then prepended to the form.

You can see my current page at www.wildtrout.org. If you view the page source you will see the issue. The token has already been rendered and will never get updated. Can you confirm I have done this correct and that the JS injection will not work.

Roger

**Comment by jsmrtn** [comment]
Yes you're right, @rogerdawkins, the README code wouldn't work. I've updated it to make this clearer, now. 

https://github.com/scaramangagency/craft-litespeedcache/blob/3.0.0/README.md#forms

Your solution to make an AJAX call to an uncached page (or controller action) would be the correct one.

Thanks!
