### ISSUE TITLE
Craft 3.5.1 update, internal error on clearing the LS cache

### ISSUE THREAD

**Issue by moondawg69** [thoughtfulweb/craft-litespeedcache#6]
Hi,

Latest 3.5.1 update, went to clear the LS cache in the control pane which results in an internal error, checked the craft log, which is below, if that is any help with a fix. Cheers 👍 

2020-08-06 17:41:11 [-][1][49b72958c98fc0785b7f76fe425f46a8][error][Error] Error: Call to a member function getAcceptsJson() on string in /home/techfellowco/craft/vendor/craftcms/cms/src/web/Controller.php:183
Stack trace:
#0 /home/techfellowco/craft/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('force-clear', Array)
#1 /home/techfellowco/craft/vendor/craftcms/cms/src/web/Application.php(294): yii\base\Module->runAction('lite-speed-cach...', Array)
#2 /home/techfellowco/craft/vendor/craftcms/cms/src/web/Application.php(597): craft\web\Application->runAction('lite-speed-cach...', Array)
#3 /home/techfellowco/craft/vendor/craftcms/cms/src/web/Application.php(273): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#4 /home/techfellowco/craft/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#5 /home/techfellowco/public_html/index.php(21): yii\base\Application->run()
#6 {main}
2020-08-06 17:41:11 [-][1][49b72958c98fc0785b7f76fe425f46a8][info][application] $_GET = [
    'p' => 'admin/lite-speed-cache'
]

$_POST = [
    'CRAFT_CSRF_TOKEN' => '••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••'
    'action' => 'lite-speed-cache/litespeed-cache/force-clear'
    'redirect' => '9cf2e2da3747b7fc67f6b1d9621d0617d00b22540daf42cf4d5ddf4c18e86ed8lite-speed-cache'
]

$_FILES = []

$_COOKIE = [
    '1031b8c41dfff97a311a7ac99863bdc5_identity' => '2ff9d741c42250e929609bdafd7aaac96d35d677f02155c0998918273025b5efa:2:{i:0;s:41:\"1031b8c41dfff97a311a7ac99863bdc5_identity\";i:1;s:246:\"[1,\"[\\\"Z4VIloGRoqZTi95XBy9pw02wXDxpqm7z71pkvkB4nwBGh0w-i_j0z-79ItUm86J8QMXMRrKq1uEgeY-cjRwW67nHNyslykWkJQNF\\\",null,\\\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Safari/605.1.15\\\"]\",3600]\";}'
    '1031b8c41dfff97a311a7ac99863bdc5_username' => '79a8db28ae33a43275ce4da4ab7f31bdc177d02ef5dd7130815ae0a50a6541b3a:2:{i:0;s:41:\"1031b8c41dfff97a311a7ac99863bdc5_username\";i:1;s:7:\"tfadmin\";}'
    'CRAFT_CSRF_TOKEN' => '•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••'
    'CraftSessionId' => '49b72958c98fc0785b7f76fe425f46a8'
]

$_SESSION = [
    'bd62416aa8538ede709019a5e113eea5__flash' => []
    '1031b8c41dfff97a311a7ac99863bdc5__token' => '••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••'
    '1031b8c41dfff97a311a7ac99863bdc5__id' => 1
    '1031b8c41dfff97a311a7ac99863bdc5__expire' => 1596735671
]

$_SERVER = [
    'PATH' => '/usr/local/bin:/bin:/usr/bin'
    'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'
    'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br'
    'HTTP_ACCEPT_LANGUAGE' => 'en-gb'
    'CONTENT_TYPE' => 'application/x-www-form-urlencoded'
    'CONTENT_LENGTH' => '721'
    'HTTP_COOKIE' => '1031b8c41dfff97a311a7ac99863bdc5_identity=2ff9d741c42250e929609bdafd7aaac96d35d677f02155c0998918273025b5efa%3A2%3A%7Bi%3A0%3Bs%3A41%3A%221031b8c41dfff97a311a7ac99863bdc5_identity%22%3Bi%3A1%3Bs%3A246%3A%22%5B1%2C%22%5B%5C%22Z4VIloGRoqZTi95XBy9pw02wXDxpqm7z71pkvkB4nwBGh0w-i_j0z-79ItUm86J8QMXMRrKq1uEgeY-cjRwW67nHNyslykWkJQNF%5C%22%2Cnull%2C%5C%22Mozilla%2F5.0%20%28Macintosh%3B%20Intel%20Mac%20OS%20X%2010_15_6%29%20AppleWebKit%2F605.1.15%20%28KHTML%2C%20like%20Gecko%29%20Version%2F13.1.2%20Safari%2F605.1.15%5C%22%5D%22%2C3600%5D%22%3B%7D; 1031b8c41dfff97a311a7ac99863bdc5_username=79a8db28ae33a43275ce4da4ab7f31bdc177d02ef5dd7130815ae0a50a6541b3a%3A2%3A%7Bi%3A0%3Bs%3A41%3A%221031b8c41dfff97a311a7ac99863bdc5_username%22%3Bi%3A1%3Bs%3A7%3A%22tfadmin%22%3B%7D; CRAFT_CSRF_TOKEN=778a2ab913cc2655c15a3a72bff1f26d11e280ad14a932010cdac765d8fdb3baa%3A2%3A%7Bi%3A0%3Bs%3A16%3A%22CRAFT_CSRF_TOKEN%22%3Bi%3A1%3Bs%3A208%3A%22ciCnk9L1tHm1PMJvD71EWBdWz6bUDzDpZLSzwg_2%7C53118c47479e4423a97ae68aeac73016021613f4430e7349829c6fad2b909091ciCnk9L1tHm1PMJvD71EWBdWz6bUDzDpZLSzwg_2%7C1%7C%242y%2413%24Ic0B.J0hl2yLDY.TxKKNM.HWrEi1qIn43JjRzxiTTIL4apV1Vwn6K%22%3B%7D; CraftSessionId=49b72958c98fc0785b7f76fe425f46a8'
    'HTTP_HOST' => 'www.techfellow.co.uk'
    'HTTP_REFERER' => 'https://www.blah/admin/lite-speed-cache'
    'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Safari/605.1.15'
    'HTTP_ORIGIN' => 'https://www.blah'
    'DOCUMENT_ROOT' => '/home/techfellowco/public_html'
    'REMOTE_ADDR' => '5.70.244.131'
    'REMOTE_PORT' => '49392'
    'SERVER_PORT' => '443'
    'REQUEST_SCHEME' => 'https'
    'REQUEST_URI' => '/admin/lite-speed-cache'
    'REDIRECT_URL' => '/admin/lite-speed-cache'
    'GEOIP_ADDR' => '5.70.244.131'
    'GEOIP_COUNTRY_CODE' => 'GB'
    'GEOIP_COUNTRY_NAME' => 'United Kingdom'
    'GEOIP_CONTINENT_CODE' => 'EU'
    'HTTPS' => 'on'
    'REDIRECT_STATUS' => '200'
    'CRAWLER_USLEEP' => '50000'
    'CRAWLER_LOAD_LIMIT' => '20'
    'X_SPDY' => 'HTTP2'
    'SSL_PROTOCOL' => 'TLSv1.3'
    'SSL_CIPHER' => 'TLS_AES_128_GCM_SHA256'
    'SSL_CIPHER_USEKEYSIZE' => '128'
    'SSL_CIPHER_ALGKEYSIZE' => '128'
    'SCRIPT_FILENAME' => '/home/techfellowco/public_html/index.php'
    'QUERY_STRING' => 'p=admin/lite-speed-cache'
    'SCRIPT_URI' => 'https://www.blah.co.uk/admin/lite-speed-cache'
    'SCRIPT_URL' => '/admin/lite-speed-cache'
    'SCRIPT_NAME' => '/index.php'
    'SERVER_PROTOCOL' => 'HTTP/1.1'
    'SERVER_SOFTWARE' => 'LiteSpeed'
    'REQUEST_METHOD' => 'POST'
    'X-LSCACHE' => 'on,crawler'
    'PHP_SELF' => '/index.php'
    'REQUEST_TIME_FLOAT' => 1596732071.5681
    'REQUEST_TIME' => 1596732071
    'ENVIRONMENT' => 'production'
    'SECURITY_KEY' => '••••••••••••••••••••••••••••••••'
    'DB_DSN' => ';'
    'DB_USER' => ''
    'DB_PASSWORD' => '•••••••••••••••'
    'DB_SCHEMA' => ''
    'DB_TABLE_PREFIX' => ''
    'DEFAULT_SITE_URL' => '
]

**Comment by jsmrtn** [comment]
@moondawg69 [1.2.6](https://github.com/scaramangagency/craft-litespeedcache/releases/tag/1.2.6) resolves this issue for you.

**Comment by moondawg69** [comment]
Thank you @joshua-martin much appreciated.

**Comment by moondawg69** [comment]
@joshua-martin Strange?

~/craft $ ./craft update
Fetching available updates ... done
You’re all up-to-date!
