### ISSUE TITLE
Clear Litespeed Cache doesn't work

### ISSUE THREAD

**Issue by jhubb-io** [thoughtfulweb/craft-litespeedcache#8]
The Clear Litespeed Cache button is returning with permissions errors.
scandir(/home/innoluxe/lscache/0): failed to open dir: Permission denied

Folders are set to 0770

**Comment by jsmrtn** [comment]
I'm afraid this doesn't sound like a plugin issue, this will be an environment issue. I can only presume that the user running PHP doesn't have permissions to access the lscache folder–I would suggest checking your PHP user is in the same group as the group that's applied to the `.lscache` folder.
